FROM percona/percona-server-mongodb:7.0.16
USER root

RUN mkdir -p /var/cache/yum /var/cache/dnf \
 && microdnf install -y iproute iptables \
 && microdnf clean all \
 && rm -rf /var/cache/yum /var/cache/dnf

