net:
  bindIpAll: true
  port: 27017

security:
  ldap:
    servers: "ldap.rr:389,ldap.rr:389,ldap.rr:389,ldap.rr:389,ldap.rr:389"
    transportSecurity: none
    timeoutMS: 10000
    bind:
      method: simple
      queryUser: "CN=svc_mongoldap,OU=Service Accounts,dc=example,dc=com"
      queryPassword: "querypass"
    userToDNMapping: '[{ "match": "(.+)", "ldapQuery": "dc=example,dc=com??sub?(uid={0})" }]'
    authz:
      queryTemplate: "ou=Groups,dc=example,dc=com??sub?(&(objectClass=groupOfNames)(member={USER}))"
    validateLDAPServerConfig: true

setParameter:
  authenticationMechanisms: SCRAM-SHA-1,SCRAM-SHA-256,PLAIN

